version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: foody
      MYSQL_USER: "mySql"
      MYSQL_PASSWORD: "1234"
    ports:
#      - 포트 바인딩
      - "3306:3306"
    networks:
      - msa-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  msa-network:

volumes:
  db_data:
